spring:
  messages:
    basename: message, config.i18n.messages
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:hyunbennylog
    username: sa
    password:
    driver-class-name: org.h2.Driver