spring:
  messages:
    basename: message, config.i18n.messages
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true # 웹에서 요청이 넘어 왔을 때 1로 보정을 해주는 역할
        default-page-size: 5

  datasource:
    url: jdbc:h2:mem:hyunbennylog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true

  sql:
    init:
      mode: always