### 테스트 요청

GET http://localhost:8080/foo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.NX3yPYdLm5p2_q8FzQ7C9IMAAMtA7tro79pJpScvSyc
#Cookie: HYUNBENNYLOG_SESSION_ID=c71feeb7-86bc-46e5-afe8-7ff775ad1e8f
#Authorization: hyunbenny
#Authorization: {{commonAUthorization}}


